version: '3.7'

services:
  nginx:
    image: motion8/nginx:1.16-dev
    ports:
      - 80:80
    environment:
      # proxy_pass to...
      APP_PORT: 8080
      APP_DNS: app
    depends_on:
      - app

  app:
    image: fastapi-bp
    build:
      context: .
      dockerfile: Dockerfile
    command: /start-reload.sh
    restart: always
    environment:
      # Gunicorn
      PORT: 8080
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8080:8080
    volumes:
      - ./app:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./data:/test-data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example